### ISSUE TITLE
It's possible to change FAN SPEED ?

### ISSUE THREAD

**Issue by mr7ndr3** [aleksamagicka/waterforce-hwmon#3]
Hi, I hope this message find you well...

1 Thank you for your work!!!

Now with this, I can see the FAN SPEED, but I'm hoping you could help me **change the FAN RPM**.
At this point, I open a Virtual Windows and pass-through the 'Bus 001 Device 007: ID 1044:7a4d Chu Yuen Enterprise Co., Ltd Castor' to Windows, and then with AORUS ENGINE or GCC, I can change the FAN SPEED and, if needed, shut down the RGB. But if I could do it in Linux, it would be perfect...

doesn't work with:
echo "1000" > /sys/class/hwmon/hwmon8/fan1_target 
echo "1000" | sudo tee /sys/class/hwmon/hwmon8/fan1_target
echo "1000" | sudo tee /sys/class/hwmon/hwmon8/fan1_input

I've tried _OpenRGB_ _liquictl_ and nothing even with:
sudo modprobe i2c-dev
sudo modprobe i2c-i801
sudo i2cdetect -l
sudo sensors-detect
fancontrol
sudo pwmconfig

**Comment by aleksamagicka** [comment]
Looks like you've got this [sorted](https://github.com/liquidctl/liquidctl/issues/167#issuecomment-1567442287) with a fw update, closing.
